### ISSUE TITLE
Bug: Cannot read property 'date' of undefined

### ISSUE THREAD

**Issue by shielsasaurus** [IonicaBizau/github-contributions#11]
OS: Windows
Node Ver: 10.x

Console outputs: 

````cmd
C:\Users\Luke Shiels\gh-contributions>npm start

> gh-contributions@0.0.0 start C:\Users\Luke Shiels\gh-contributions
> node server.js

Listening on 9000
/css/gh-style.css - Not Modified
/js/jquery.min.js - Not Modified
/bootstrap/js/bootstrap.min.js - Not Modified
/js/index.js - Not Modified
/bootstrap/css/bootstrap.min.css - Not Modified
/css/github.css - Not Modified

C:\Users\Luke Shiels\gh-contributions\contributions.js:60
            options.dates.push(year[p.x - 1][p.y - 1].date);
                                                     ^
TypeError: Cannot read property 'date' of undefined
    at Object.module.exports.getRepo (C:\Users\Luke Shiels\gh-contributions\co
ributions.js:60:54)
    at C:\Users\Luke Shiels\gh-contributions\server.js:53:27
    at IncomingMessage.<anonymous> (C:\Users\Luke Shiels\gh-contributions\serv
.js:107:13)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

npm ERR! gh-contributions@0.0.0 start: `node server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the gh-contributions@0.0.0 start script.
npm ERR! This is most likely a problem with the gh-contributions package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls gh-contributions
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\n
ejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd C:\Users\Luke Shiels\gh-contributions
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Luke Shiels\gh-contributions\npm-debug.log
npm ERR! not ok code 0

C:\Users\Luke Shiels\gh-contributions>

````

The client on the browser just says: `Error: undefined`.

**Comment by silviubogan** [comment]
@IonicaBizau, I can start working for Windows support if you assign this issue to me.

**Comment by IonicaBizau** [comment]
@silviubogan This should be working on Windows.
